name: Build and Deploy to Docker

on:
  push:
    branches:
      - hostinger_master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - hostinger_master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the project with Maven and skip tests
      - name: Build the project
        run: |
          mvn clean install package -DskipTests

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./yudao-server/Dockerfile
          push: true
          platforms: linux/amd64  # Ensures it's built for AMD64
          tags: |
            ngjingchong/api-server:amd64
            ngjingchong/api-server:${{ github.sha }}
          cache-from: type=registry,ref=ngjingchong/api-server:amd64
          cache-to: type=inline

      - name: Verify the built image
        run: docker manifest inspect ngjingchong/api-server:amd64

      - name: Deploy to Hostinger VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            docker pull ngjingchong/api-server:amd64
            docker stop api-server || true
            docker rm api-server || true
            docker rmi $(docker images -f "dangling=true" -q) || true
            docker run -d -p 48080:48080 --name api-server ngjingchong/api-server:amd64
